server.port=8083
spring.application.name=leaderboard-service
spring.datasource.url=jdbc:postgresql://localhost:5433/leaderboarddb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=aigo
spring.datasource.password=aigo_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jackson.serialization.write-dates-as-timestamps=false
